### PR TITLE
Subsystems as robot class constructor arguments

### PR DESCRIPTION
**Pull request by Jamdan2**
I feel like it would be nice if subsystems could be passed as constructor parameters to the main robot class, just as a little usability shortcut. Then we could be all like
```
class Poe : Robot(
	Drivetrain,
	Lift,
	Intake
)
```
which would be nice

### CODE REVIEW

**Comment by Jamdan2** [comment]
Oops, somehow my other commit got thrown in there

**Comment by andrewda** [comment]
Sorry for the noise, just changed base to take a peek at the actual diff.

Anyways, this is interesting. What benefit do you think this provides? Just more separation between actual robot code, I presume? And just to be clear, I assume it would change this file:

```kotlin
class Poe : Robot() {
    override fun onCreate() {
        Drivetrain
        Intake
        Elevator
        Climber
        Auto
        Modes
        Lights

        UDPServer.start()
        CameraServer.getInstance().startAutomaticCapture()

        initPreferences()
        logTelemetry()
    }
}
```

To this:

```kotlin
class Poe : Robot(
    Drivetrain
    Intake
    Elevator
    Climber
    Auto
    Modes
    Lights
) {
    override fun onCreate() {
        UDPServer.start()
        CameraServer.getInstance().startAutomaticCapture()

        initPreferences()
        logTelemetry()
    }
}
```

**Comment by Jamdan2** [comment]
Hmm, wouldn't you have to manually add the subsystems to the LifecycleDistributor?

**Comment by andrewda** [comment]
https://github.com/sertain/sertain/blob/6ccac283921bf7320d2505901946db7302349eb7/core/src/main/kotlin/org/sertain/command/Subsystem.kt#L16

They should be automatically added to the RobotLifecycle through the `initSendable()` method (called automatically when Subsystem is initialized). As far as I can tell, all this does is move the place where Subsystems are added to the lifecycle. Maybe I'm missing something, though.

**Comment by Jamdan2** [comment]
I actually removed that in this commit, because adding the dashboard has nothing to do with adding a life-cycle listener.

**Comment by andrewda** [comment]
Okay, let's try this along with your other PR on Friday. If it works then LGTM.

BTW can you rebase your other commit out of this PR? If the other PR is merged first it'll just cause conflicts we'll have to deal with later.

**Comment by Jamdan2** [comment]
How would I do that? I tried on my local repo and I totally screwed the entire history over.
Git confuses me ❓ 😕 ❓

**Comment by andrewda** [comment]
https://www.clock.co.uk/insight/deleting-a-git-commit

**Comment by Jamdan2** [comment]
Tried what they suggested and it didn't work.
I used `git rebase --onto usability~6 usability~5 usability`
It did something, but definitely did not delete the commit from the branch
Did I reference the wrong commits?

**Comment by andrewda** [comment]
Haha okay, I'll try to see what's up in a bit

**Pull request merged**
