### PR TITLE
Add main robot class

### LINKED ISSUE #5: Create new primary Robot interface
Rewrite `IterativeRobot` so we don't have to add `Scheduler.getInstance().run()` bullshit everywhere

cc @SUPERCILEX

### PR DESCRIPTION
**Pull request by andrewda**
Closes #5

### CODE REVIEW

**Comment by andrewda** [comment]
@SUPERCILEX lmk when you're done and want me to fix conflicts.

**Comment by andrewda** [comment]
@SUPERCILEX fixed it for you ;)

**Comment by SUPERCILEX** [comment]
@andrewda Oh lol, I thought it got messed up.

**Comment by SUPERCILEX** [comment]
Anyway, I made a bunch of changes to Kotlinize it. Are you cool with those changes?

**Comment by SUPERCILEX** [comment]
Merging so I can make progress, we can rebase later if necessary.

**Pull request merged**
