### PR TITLE
Add CONTRIBUTING.md

### LINKED ISSUE #21: Add contributing guide

### PR DESCRIPTION
**Pull request by andrewda**
Closes #21

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@andrewda please use `Fixes`, it sounds better. 😄 (Unless you have an argument against that?)

**Comment by SUPERCILEX** [comment]
@andrewda What do you think of 3ebec8f? I fixed some typos and removed the contributor list thing since:
1. We don't have that file yet
1. I kinda hate those things since they're always out-of-date and GitHub has a much better list anyway

**Comment by andrewda** [comment]
LGTM. I use closes for features and fixes for bugs (GitPoint/coals habit but I like it)

**Comment by SUPERCILEX** [comment]
@andrewda Oh cool, that makes a ton of sense! I'll use that too in the future. 👍

**Pull request merged**
